sudo: required

services: docker

before_install:
  - docker-compose up --build -d
  - docker login -u "$HEROKU_USERNAME" -p "$HEROKU_API_KEY" registry.heroku.com

script: 
  - docker-compose exec --env 'RAILS_ENV=test' app rails db:create
  - docker-compose exec --env 'RAILS_ENV=test' app rails db:migrate
  - docker-compose exec --env 'RAILS_ENV=test' app rails test

deploy:
  provider: script
  script:
    docker build -t registry.heroku.com/$HEROKU_APP_NAME/app -f Dockerfile.prod .;
    docker push registry.heroku.com/$HEROKU_APP_NAME/app;
    heroku run --app $HEROKU_APP_NAME rails db:migrate;
  on:
    branch: master